import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./../styles/global.scss";
import { Menu } from "@/components";
import { MobxProvider } from "./providers/MobxProvider";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <MobxProvider>
        <div className="layout">
          <Menu />
          <main className="content">{children}</main>
        </div>
        </MobxProvider>
      </body>
    </html>
  );
}
